project:
  type: book

book:
  title: "tmp"
  author: "Jane Doe"
  date: "10/20/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
          \usepackage{mathtools}
    include-before-body: 
      text: |
          window.MathJax = {
              loader: {
                  load: ['[tex]/tagformat', '[tex]/mathtools', '[tex]/amssymb']
              },
              tex: {
                  packages: {'[+]': ['tagformat', 'mathtools', 'amssymb']},
                  tags: 'ams'
              }
          };

    keep-tex: true

